const express = require('express');
const path = require('path');
const app = express();
app.set('view engine', 'pug');
app.use(express.static(path.join(__dirname, 'public')));

const legal = {
  nomeAzienda: '"Situazione italiana aggiornata COVID19 by Luca Zonarelli"',
  nome: '"Situazione COVID19"',
  url: 'covid19.lucazonarelli.com',
  titolare: "Luca Zonarelli",
  email: "privacy@lucazonarelli.com",
};

app.get('/', function (req, res) {
  const regioni = [
    {
      "data": "2020-03-10 18:00:00",
      "stato": "ITA",
      "codice_regione": 13,
      "denominazione_regione": "Abruzzo",
      "lat": 42.35122196,
      "long": 13.39843823,
      "ricoverati_con_sintomi": 17,
      "terapia_intensiva": 9,
      "totale_ospedalizzati": 26,
      "isolamento_domiciliare": 11,
      "totale_attualmente_positivi": 37,
      "nuovi_attualmente_positivi": 7,
      "dimessi_guariti": 0,
      "deceduti": 1,
      "totale_casi": 38,
      "nuovi_positivi": 0,
      "casi_testati": 0,
      "tamponi": 310
    },
    {
      "data": "2020-03-10 18:00:00",
      "stato": "ITA",
      "codice_regione": 17,
      "denominazione_regione": "Basilicata",
      "lat": 40.63947052,
      "long": 15.80514834,
      "ricoverati_con_sintomi": 2,
      "terapia_intensiva": 0,
      "totale_ospedalizzati": 2,
      "isolamento_domiciliare": 5,
      "totale_attualmente_positivi": 7,
      "nuovi_attualmente_positivi": 2,
      "dimessi_guariti": 0,
      "deceduti": 0,
      "totale_casi": 7,
      "nuovi_positivi": 0,
      "casi_testati": 0,
      "tamponi": 148
    },
    {
      "data": "2020-03-10 18:00:00",
      "stato": "ITA",
      "codice_regione": 21,
      "denominazione_regione": "P.A. Bolzano",
      "lat": 46.49933453,
      "long": 11.35662422,
      "ricoverati_con_sintomi": 17,
      "terapia_intensiva": 1,
      "totale_ospedalizzati": 18,
      "isolamento_domiciliare": 20,
      "totale_attualmente_positivi": 38,
      "nuovi_attualmente_positivi": 29,
      "dimessi_guariti": 0,
      "deceduti": 0,
      "totale_casi": 38,
      "nuovi_positivi": 0,
      "casi_testati": 0,
      "tamponi": 36
    },
    {
      "data": "2020-03-10 18:00:00",
      "stato": "ITA",
      "codice_regione": 18,
      "denominazione_regione": "Calabria",
      "lat": 38.10922769,
      "long": 15.6434527,
      "ricoverati_con_sintomi": 8,
      "terapia_intensiva": 2,
      "totale_ospedalizzati": 10,
      "isolamento_domiciliare": 1,
      "totale_attualmente_positivi": 11,
      "nuovi_attualmente_positivi": 2,
      "dimessi_guariti": 2,
      "deceduti": 0,
      "totale_casi": 13,
      "nuovi_positivi": 0,
      "casi_testati": 0,
      "tamponi": 360
    },
    {
      "data": "2020-03-10 18:00:00",
      "stato": "ITA",
      "codice_regione": 15,
      "denominazione_regione": "Campania",
      "lat": 40.83956555,
      "long": 14.25084984,
      "ricoverati_con_sintomi": 33,
      "terapia_intensiva": 8,
      "totale_ospedalizzati": 41,
      "isolamento_domiciliare": 85,
      "totale_attualmente_positivi": 126,
      "nuovi_attualmente_positivi": 7,
      "dimessi_guariti": 1,
      "deceduti": 0,
      "totale_casi": 127,
      "nuovi_positivi": 0,
      "casi_testati": 0,
      "tamponi": 1141
    },
    {
      "data": "2020-03-10 18:00:00",
      "stato": "ITA",
      "codice_regione": 8,
      "denominazione_regione": "Emilia Romagna",
      "lat": 44.49436681,
      "long": 11.3417208,
      "ricoverati_con_sintomi": 669,
      "terapia_intensiva": 98,
      "totale_ospedalizzati": 767,
      "isolamento_domiciliare": 650,
      "totale_attualmente_positivi": 1417,
      "nuovi_attualmente_positivi": 131,
      "dimessi_guariti": 31,
      "deceduti": 85,
      "totale_casi": 1533,
      "nuovi_positivi": 0,
      "casi_testati": 0,
      "tamponi": 5494
    },
    {
      "data": "2020-03-10 18:00:00",
      "stato": "ITA",
      "codice_regione": 6,
      "denominazione_regione": "Friuli Venezia Giulia",
      "lat": 45.6494354,
      "long": 13.76813649,
      "ricoverati_con_sintomi": 27,
      "terapia_intensiva": 6,
      "totale_ospedalizzati": 33,
      "isolamento_domiciliare": 77,
      "totale_attualmente_positivi": 110,
      "nuovi_attualmente_positivi": 21,
      "dimessi_guariti": 3,
      "deceduti": 3,
      "totale_casi": 116,
      "nuovi_positivi": 0,
      "casi_testati": 0,
      "tamponi": 1602
    },
    {
      "data": "2020-03-10 18:00:00",
      "stato": "ITA",
      "codice_regione": 12,
      "denominazione_regione": "Lazio",
      "lat": 41.89277044,
      "long": 12.48366722,
      "ricoverati_con_sintomi": 50,
      "terapia_intensiva": 15,
      "totale_ospedalizzati": 65,
      "isolamento_domiciliare": 34,
      "totale_attualmente_positivi": 99,
      "nuovi_attualmente_positivi": 5,
      "dimessi_guariti": 11,
      "deceduti": 6,
      "totale_casi": 116,
      "nuovi_positivi": 0,
      "casi_testati": 0,
      "tamponi": 3591
    },
    {
      "data": "2020-03-10 18:00:00",
      "stato": "ITA",
      "codice_regione": 7,
      "denominazione_regione": "Liguria",
      "lat": 44.41149315,
      "long": 8.9326992,
      "ricoverati_con_sintomi": 57,
      "terapia_intensiva": 29,
      "totale_ospedalizzati": 86,
      "isolamento_domiciliare": 42,
      "totale_attualmente_positivi": 128,
      "nuovi_attualmente_positivi": 31,
      "dimessi_guariti": 5,
      "deceduti": 8,
      "totale_casi": 141,
      "nuovi_positivi": 0,
      "casi_testati": 0,
      "tamponi": 694
    },
    {
      "data": "2020-03-10 18:00:00",
      "stato": "ITA",
      "codice_regione": 3,
      "denominazione_regione": "Lombardia",
      "lat": 45.46679409,
      "long": 9.190347404,
      "ricoverati_con_sintomi": 3319,
      "terapia_intensiva": 466,
      "totale_ospedalizzati": 3785,
      "isolamento_domiciliare": 642,
      "totale_attualmente_positivi": 4427,
      "nuovi_attualmente_positivi": -63,
      "dimessi_guariti": 896,
      "deceduti": 468,
      "totale_casi": 5791,
      "nuovi_positivi": 0,
      "casi_testati": 0,
      "tamponi": 21479
    },
    {
      "data": "2020-03-10 18:00:00",
      "stato": "ITA",
      "codice_regione": 11,
      "denominazione_regione": "Marche",
      "lat": 43.61675973,
      "long": 13.5188753,
      "ricoverati_con_sintomi": 152,
      "terapia_intensiva": 54,
      "totale_ospedalizzati": 206,
      "isolamento_domiciliare": 175,
      "totale_attualmente_positivi": 381,
      "nuovi_attualmente_positivi": 68,
      "dimessi_guariti": 0,
      "deceduti": 13,
      "totale_casi": 394,
      "nuovi_positivi": 0,
      "casi_testati": 0,
      "tamponi": 1437
    },
    {
      "data": "2020-03-10 18:00:00",
      "stato": "ITA",
      "codice_regione": 14,
      "denominazione_regione": "Molise",
      "lat": 41.55774754,
      "long": 14.65916051,
      "ricoverati_con_sintomi": 3,
      "terapia_intensiva": 3,
      "totale_ospedalizzati": 6,
      "isolamento_domiciliare": 9,
      "totale_attualmente_positivi": 15,
      "nuovi_attualmente_positivi": 1,
      "dimessi_guariti": 0,
      "deceduti": 0,
      "totale_casi": 15,
      "nuovi_positivi": 0,
      "casi_testati": 0,
      "tamponi": 225
    },
    {
      "data": "2020-03-10 18:00:00",
      "stato": "ITA",
      "codice_regione": 1,
      "denominazione_regione": "Piemonte",
      "lat": 45.0732745,
      "long": 7.680687483,
      "ricoverati_con_sintomi": 306,
      "terapia_intensiva": 66,
      "totale_ospedalizzati": 372,
      "isolamento_domiciliare": 64,
      "totale_attualmente_positivi": 436,
      "nuovi_attualmente_positivi": 99,
      "dimessi_guariti": 0,
      "deceduti": 17,
      "totale_casi": 453,
      "nuovi_positivi": 0,
      "casi_testati": 0,
      "tamponi": 2374
    },
    {
      "data": "2020-03-10 18:00:00",
      "stato": "ITA",
      "codice_regione": 16,
      "denominazione_regione": "Puglia",
      "lat": 41.12559576,
      "long": 16.86736689,
      "ricoverati_con_sintomi": 28,
      "terapia_intensiva": 6,
      "totale_ospedalizzati": 34,
      "isolamento_domiciliare": 21,
      "totale_attualmente_positivi": 55,
      "nuovi_attualmente_positivi": 9,
      "dimessi_guariti": 1,
      "deceduti": 3,
      "totale_casi": 59,
      "nuovi_positivi": 0,
      "casi_testati": 0,
      "tamponi": 747
    },
    {
      "data": "2020-03-10 18:00:00",
      "stato": "ITA",
      "codice_regione": 20,
      "denominazione_regione": "Sardegna",
      "lat": 39.21531192,
      "long": 9.110616306,
      "ricoverati_con_sintomi": 9,
      "terapia_intensiva": 0,
      "totale_ospedalizzati": 9,
      "isolamento_domiciliare": 11,
      "totale_attualmente_positivi": 20,
      "nuovi_attualmente_positivi": 1,
      "dimessi_guariti": 0,
      "deceduti": 0,
      "totale_casi": 20,
      "nuovi_positivi": 0,
      "casi_testati": 0,
      "tamponi": 204
    },
    {
      "data": "2020-03-10 18:00:00",
      "stato": "ITA",
      "codice_regione": 19,
      "denominazione_regione": "Sicilia",
      "lat": 38.11569725,
      "long": 13.3623567,
      "ricoverati_con_sintomi": 17,
      "terapia_intensiva": 2,
      "totale_ospedalizzati": 19,
      "isolamento_domiciliare": 41,
      "totale_attualmente_positivi": 60,
      "nuovi_attualmente_positivi": 8,
      "dimessi_guariti": 2,
      "deceduti": 0,
      "totale_casi": 62,
      "nuovi_positivi": 0,
      "casi_testati": 0,
      "tamponi": 955
    },
    {
      "data": "2020-03-10 18:00:00",
      "stato": "ITA",
      "codice_regione": 9,
      "denominazione_regione": "Toscana",
      "lat": 43.76923077,
      "long": 11.25588885,
      "ricoverati_con_sintomi": 91,
      "terapia_intensiva": 40,
      "totale_ospedalizzati": 131,
      "isolamento_domiciliare": 129,
      "totale_attualmente_positivi": 260,
      "nuovi_attualmente_positivi": 54,
      "dimessi_guariti": 3,
      "deceduti": 1,
      "totale_casi": 264,
      "nuovi_positivi": 0,
      "casi_testati": 0,
      "tamponi": 2573
    },
    {
      "data": "2020-03-10 18:00:00",
      "stato": "ITA",
      "codice_regione": 22,
      "denominazione_regione": "P.A. Trento",
      "lat": 46.06893511,
      "long": 11.12123097,
      "ricoverati_con_sintomi": 19,
      "terapia_intensiva": 3,
      "totale_ospedalizzati": 22,
      "isolamento_domiciliare": 28,
      "totale_attualmente_positivi": 50,
      "nuovi_attualmente_positivi": 17,
      "dimessi_guariti": 2,
      "deceduti": 0,
      "totale_casi": 52,
      "nuovi_positivi": 0,
      "casi_testati": 0,
      "tamponi": 399
    },
    {
      "data": "2020-03-10 18:00:00",
      "stato": "ITA",
      "codice_regione": 10,
      "denominazione_regione": "Umbria",
      "lat": 43.10675841,
      "long": 12.38824698,
      "ricoverati_con_sintomi": 8,
      "terapia_intensiva": 2,
      "totale_ospedalizzati": 10,
      "isolamento_domiciliare": 27,
      "totale_attualmente_positivi": 37,
      "nuovi_attualmente_positivi": 9,
      "dimessi_guariti": 0,
      "deceduti": 0,
      "totale_casi": 37,
      "nuovi_positivi": 0,
      "casi_testati": 0,
      "tamponi": 260
    },
    {
      "data": "2020-03-10 18:00:00",
      "stato": "ITA",
      "codice_regione": 2,
      "denominazione_regione": "Valle d'Aosta",
      "lat": 45.73750286,
      "long": 7.320149366,
      "ricoverati_con_sintomi": 2,
      "terapia_intensiva": 0,
      "totale_ospedalizzati": 2,
      "isolamento_domiciliare": 15,
      "totale_attualmente_positivi": 17,
      "nuovi_attualmente_positivi": 2,
      "dimessi_guariti": 0,
      "deceduti": 0,
      "totale_casi": 17,
      "nuovi_positivi": 0,
      "casi_testati": 0,
      "tamponi": 89
    },
    {
      "data": "2020-03-10 18:00:00",
      "stato": "ITA",
      "codice_regione": 5,
      "denominazione_regione": "Veneto",
      "lat": 45.43490485,
      "long": 12.33845213,
      "ricoverati_con_sintomi": 204,
      "terapia_intensiva": 67,
      "totale_ospedalizzati": 271,
      "isolamento_domiciliare": 512,
      "totale_attualmente_positivi": 783,
      "nuovi_attualmente_positivi": 89,
      "dimessi_guariti": 47,
      "deceduti": 26,
      "totale_casi": 856,
      "nuovi_positivi": 0,
      "casi_testati": 0,
      "tamponi": 16643
    }
  ];
  res.render('pages/index', { regioni: regioni });
});

app.get('/credits', function (req, res) {
  res.render('pages/legal/credits');
});

app.get('/privacy', function (req, res) {
  res.render('pages/legal/privacy', legal);
});

app.get('/cookie', function (req, res) {
  res.render('pages/legal/cookie', legal);
});

const server = app.listen(8081, function () {
 const host = server.address().address;
 const port = server.address().port;

 console.log("Example app listening at http://%s:%s", host, port)
});
